### ISSUE TITLE
Understanding of project.

### ISSUE THREAD

**Issue by ritik1604** [ScottBouloutian/steganography#1]
Hey,
Please help me in understanding the code. What is the significance of some codes?

**Comment by ScottBouloutian** [comment]
I wrote this a while ago so it is not very fresh in my memory. The readme and comments in the code should explain the basic principles being used. The code combines a few different concepts. Least significant bit steganography is used to hide a bit encoded message in the image. Linear block codes are used as a means of error correction.

**Comment by ritik1604** [comment]
I don't understand the use of linear block codes here. If I remove the process of linear block codes, then what difference will it create?

**Comment by ScottBouloutian** [comment]
I'm not entirely sure. For simple use cases at least it wouldn't create any difference. Since the message is also hidden redundantly throughout the image, error correction would still be possible if some parts of the image were destroyed.
